### ISSUE TITLE
GPU requirements 

### ISSUE THREAD

**Issue by ejarkm** [lucidrains/PaLM-rlhf-pytorch#5]
Hi, first of all thanks for your work. I will definitely give it a try.

I was wondering if you could share some information about the training time and which GPUs you needed for train the model and if you have some recommendations about the size of the datasets you used.

Thanks a lot once again and merry Christmas!

**Comment by James4Ever0** [comment]
This model hasn't been trained by many, since PaLM is exclusive to google and this repo is open-source alternative.

The model size is configurable through parameters, though smaller models train faster, bigger models perform better and for PaLM it has advantage on model scaling, meaning it does not get stuck on bigger size.

**Comment by James4Ever0** [comment]
For datasets you can check [Eleuther.ai](https://www.eleuther.ai/).

**Comment by ejarkm** [comment]
Thanks a lot for your reply, this is really useful information :)
